### ISSUE TITLE
UI size configuration

### ISSUE THREAD

**Issue by Alvarocz** [arcticicestudio/nord-atom-ui#35]
I love this, but i like SMALL tabs like panels and project tree items.

**Comment by arcticicestudio** [comment]
I planned to implement theme settings (like the One Dark UI next to the theme selection drop-down) which will also provide an option to disable the full-width tabs.

**Comment by Alvarocz** [comment]
That well, it would be excellent

**Comment by arcticicestudio** [comment]
Currently I'm busy at work and don't know when I'll have time again to start working on the theme settings feature.
In the meantime, you can add this CSS code to your personal `style.less` file to disable the full-width tabs feature.
```css
.tab-bar {
  width: auto;;

  .tab {
    width: inherit;
  }

  .tab.active,
  .tab:hover.active {
    width: inherit;
  }
}
```
The `styles.less` file is located in Atom's home directory (`~/.atom` / `$ATOM_HOME`).
You can also open it from inside Atom via the Command Palette Overlay ("Open Your Stylesheet") or via the menu navigation (*Edit -> Stylesheet*).
