### ISSUE TITLE
Font size for tree view

### ISSUE THREAD

**Issue by yozzz** [arcticicestudio/nord-atom-ui#55]
Thanks for great theme!
How I can change font size for `.tree_view` via `style.less`? 

I have tried to set font-size like this, but didn't help
```
.tree-view {
  font-size: 13px;
}
```

**Comment by arcticicestudio** [comment]
Nice to hear you like it 😄 
There is a partically implemented feature #50 to set the UI font size which will be continued as soon as I've got some freetime for it.

<p align="center"><strong>Default 14px</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/21073555/01896a86-bee2-11e6-9ace-78416fbbb4ac.png"/><br><strong>Custom 10px</strong><br><img src="https://cloud.githubusercontent.com/assets/7836623/21073562/34a3c2ae-bee2-11e6-9d50-5aac52b7260f.png"/></p>

Feel free to check out the 🌱  [`feature/ghi-#50-theme-setting-font-size`](https://github.com/arcticicestudio/nord-atom-ui/tree/feature/ghi-%2350-theme-setting-font-size) branch to test it and report bugs and improvement suggestions.

If you'd you just like to tweak it with your personal `style.less` file until the feature is merged and released the following code should do the trick:
```less
@custom-font-size: 16px;

.tree-view {
  .project-root {
    & > .header {
      & .name {
        font-size: @custom-font-size;
      }
    }
  }

  .list-item .name {
    font-size: @custom-font-size;
  }
}

```
